version: "3.8"

services:
  api:
    environment:
      - API_PATH=server/api/
      - MEDIA_PATH=${API_PATH}media/
      - STATIC_PATH=${API_PATH}static/
    build: ./api
    volumes:
      - static_volume:${STATIC_PATH}
      - media_volume:${MEDIA_PATH}
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    volumes:
      - static_volume:${STATIC_PATH}
      - media_volume:${MEDIA_PATH}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api

volumes:
  static_volume:
  media_volume:
  postgres_data: