version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    hostname: app
    volumes:
      - ./app:/app
      - ./app/static:/app/static
      - ./app/media:/app/media
    ports:
      - "8000:8000"
