version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    hostname: nginx
    restart: on-failure
    volumes:
      - ./api/static:/api/static
      - ./api/media:/api/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: exec gunicorn -c "gunicorn_config.py" conf.wsgi
    hostname: api
    restart: on-failure
    environment:
      APP_ENV: production
    env_file:
      - ./production.env
    volumes:
      - ./api/static:/api/static
      - ./api/media:/api/media
    ports:
      - "8001:8001"
    depends_on:
      - postgres
  postgres:
    image: postgres:12.0-alpine
    hostname: postgres
    restart: on-failure
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
