version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    hostname: api
    volumes:
      - ./api:/api
      - ./api/static:/api/static
      - ./api/media:/api/media
    ports:
      - "8001:8001"
