version: "3"

services:
  ngunx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    hostname: nginx
    volumes:
      - ./api/static:/api/static
      - ./api/media:/api/media
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - api
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: exec gunicorn -c "gunicorn_config.py" conf.wsgi
    hostname: api
    volumes:
      - ./api/static:/api/static
      - ./api/media:/api/media
    ports:
      - "8001:8001"
    depends_on:
      - postgres
  postgres:
    image: postgres:12.0-alpine
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/